equinor/radix-api

api/applications/get_applications_handler.go
go.mod
go.sum

* Make use of reconciled status
* New version of operator released

Make use of reconciled status (#227)

---

api/applications/applications_controller_test.go
api/applications/applications_handler.go
docs/docs.go
models/impersonation.go

* Run patch
* Avvoid warning messages
* Avvoid warning
* Set empty ad groups if wanting reset to default

Run patch (#231)

---

api/environments/component_handler.go
api/environments/environment_controller_test.go

Allow users to stop component when in

---

api/environments/component_handler.go
api/environments/environment_controller_test.go

* Allow users to stop component when in
reconciling state
* Moved test

Allow users to stop component when in (#239)

---

api/buildsecrets/buildsecrets_handler.go
api/privateimagehubs/privateimagehubs_handler.go
go.mod
go.sum

https://equinor.atlassian.net/browse/RA-1096

Return empty lists instead of error

---

api/deployments/deployment_controller.go
api/deployments/get_deployment_handler.go
api/jobs/job_controller.go
api/jobs/log_handler.go
api/pods/pod_handler.go
docs/docs.go

* Allow for filtering logs by timestamp
* New swagger version
Co-authored-by: INGE KNUDSEN <ingeknudsen@INGEs-MacBook-Pro.local>

Ra 1315   improve logging (#246)

---

api/environments/environment_controller.go

using newline and space preserving literal in swagger doc
https://yaml-multiline.info/

Update restartComponent description

---

api/applications/applications_controller_test.go
api/environments/environment_controller.go
api/environments/environment_controller_test.go
api/environments/environment_handler.go
api/environments/secret_handler.go
charts/radix-api-dev/Chart.yaml
docs/docs.go
go.mod
go.sum

- as default deploying 2 equal RD to an env will not lead to new replicasets being deployed

add metrics + changes to deploy only

---

.gitignore
api/deployments/component_controller_test.go
api/deployments/component_handler.go
api/deployments/models/component_deployment.go
api/deployments/models/container_status.go
go.sum

RA-1524 Add state Starting to pod status in API
Status is "Starting" when a pod is running, but is not ready - it can be during a transition (starting) period or when something wrong is within pod app and it is not responding to probe.

Ra 801 indicate pod running but not ready

---

.gitignore
api/applications/applications_controller_test.go
api/applications/applications_handler.go
api/applications/models/application.go
api/applications/models/application_patchrequest.go

Ra 1371 possibility to update GitHub repo reference

---

api/applications/applications_controller_test.go
api/applications/applications_handler.go
api/jobs/job_controller_test.go
api/jobs/start_job_handler.go
go.mod
go.sum

Populates the TargetEnvs field of the RadixJob resource as it is created

Add TargetEvironments to RadixJob

---

radixconfig.yaml

Resource requests and limit set based on guide: https://www.radix.equinor.com/guides/resource-request/
GOMAXPROCS set to match CPU limit

RA-1714: update resources requests and GOMAXPROCS in radixconfig (#269)

---

api/deployments/component_controller_test.go
api/deployments/models/component_builder.go
api/environments/environment_controller_test.go
api/environments/secret_handler.go
docs/docs.go
go.mod
go.sum

Issue:
https://github.com/equinor/radix-platform/issues/372

Blobfuse flexvolume

---

api/events/event_handler.go
api/events/event_handler_test.go
api/events/models/event.go
api/events/models/event_builder.go
api/events/models/event_builder_test.go
api/events/models/object_state_builder.go
api/events/models/object_state_builder_test.go
api/events/models/pod_state_builder.go
api/events/models/pod_state_builder_test.go
docs/docs.go
go.sum

* Add pod state on warning events
* Remove commented code
* Fix event tests
* Update version
Co-authored-by: Nils Gustav Stråbø <nst@equinor.com>

Add pod state on warning events (#298)

---

api/utils/radix_middleware.go
docs/docs.go

Ignore bearer authentication and app name validation for requests to status badge

allow anonymous requests to status badge

---

api/deployments/component_handler.go
api/deployments/component_handler_test.go
docs/docs.go
go.mod
go.sum

rewrite how we get pods (replicalist) for components, job-scheduler and jobs.

103993 fix job replicalist

---

api/deployments/deployment_handler.go
api/deployments/models/deployment_builder.go
api/deployments/models/deployment_builder_test.go
api/deployments/models/deployment_summary.go
api/jobs/job_handler_test.go
docs/docs.go

Added info to DeploymentSummary about the pipeline job that built the RD.
Removed unused field appName from DeploymentBuilder

105776 extend deploy info response

---

api/applications/applications_handler.go
api/deployments/component_handler.go
api/deployments/models/component_deployment.go
docs/docs.go
go.mod
go.sum

136635 add missed status for scheduled job

---

api/buildstatus/models/badges/build-status.svg

set font size to 92. more similar to gh badge size

---

api/applications/applications_controller_test.go
api/deployments/component_controller_test.go
api/deployments/component_handler.go
api/deployments/deployment_handler.go
api/deployments/models/component_builder.go
api/deployments/models/deployment_builder.go
api/deployments/models/deployment_builder_test.go
api/environments/environment_controller_test.go
api/environments/utils.go
api/secrets/models/secret.go
api/secrets/secret_controller.go
api/secrets/secret_controller_test.go
api/secrets/secret_handler.go
api/secrets/suffix/suffix.go
api/utils/test.go
docs/docs.go
go.mod
go.sum

- Handle OAuth2 proxy secret
- Cleanup unused code and duplicate imports

61455 oauth proxy secrets

---

.gitignore
.vscode/launch.json
Makefile
README.md
api/alerting/handler.go
api/applications/applications_handler.go
api/buildsecrets/models/configuration_status.go
api/deployments/component_handler.go
api/deployments/deployment_controller_test.go
api/deployments/deployment_handler.go
api/deployments/mock/deployment_handler_mock.go
api/deployments/models/component_builder.go
api/deployments/models/component_deployment.go
api/deployments/models/component_status.go
api/deployments/models/container_status.go
api/deployments/models/deployment.go
api/deployments/models/deployment_errors.go
api/environments/component_handler.go
api/environments/environment_controller.go
api/environments/environment_controller_test.go
api/environments/environment_handler.go
api/environments/models/configuration_status.go
api/environments/models/environment_errors.go
api/jobs/models/progress_status.go
api/pods/errors.go
api/pods/pod_handler.go
api/secrets/models/configuration_status.go
api/utils/labelselector/labelselectors.go
docs/docs.go

Add oauth2 replica info to component model
Get logs for an aux replica
Restart aux service

61455 add aux component info

---

api/deployments/deployment_controller.go
api/deployments/deployment_handler.go
api/deployments/mock/deployment_handler_mock.go
api/environments/environment_controller.go
api/environments/environment_handler.go
api/jobs/log_handler.go
api/pods/pod_handler.go
api/router/server.go
api/utils/test.go
docs/docs.go
go.mod
go.sum
main.go

- Stream logs to client
- Support gzip and deflate response compression

Performance improvements (mem usage and response size) for logs

---

.gitignore
Dockerfile
Makefile
api/deployments/models/component_deployment.go
api/jobs/models/job_summary.go
api/secrets/secret_controller.go
api/secrets/secret_handler.go
api/secrets/secret_handler_test.go
docs/docs.go

Fixes invalid swagger spec causing errors when trying to generate client code from the spec

fix errors in generated swagger spec

---

api/applications/application_builder.go
api/applications/applications_controller_test.go
api/applications/applications_handler.go
api/applications/models/application_registration.go
api/applications/models/application_registration_patch.go
api/jobs/start_job_handler.go
go.mod
go.sum

* Allowed duplicated repo. Work in progress
* Fixed tests. Work in progress
* Set versions
* Fixed app-update
* Cleanup
* Added request-response objects
* Revalidate warnings only when repo changes
* Cleanup
* Rename respond with response
* Fixed radix-operator version
* Fixed unit-test
* Added radixConfigFullName to RR and application
* Added validation of radixConfigFullName with regex pattern
* tmp
* Merged with master
* Start build jobs with custom radixconfig
* Set radix-operator version

Allow radixconfig in folder and custom file name (#432)

---

api/secrets/tls_secret_validator.go

Support common formats when validating TLS private key

allow multiple private key formats

---

api/deployments/models/component_deployment.go

Added status message to unscheduled pod

---

api/alerting/alerting_controller.go
api/deployments/component_handler.go
api/deployments/deployment_handler.go
api/environments/environment_controller.go
api/environments/environment_handler.go
api/environments/utils.go

These changes are related to RBAC changes in radix-operator (PR [https://github.com/equinor/radix-operator/pull/814](https://github.com/equinor/radix-operator/pull/814))

Fix rbac errors

---

api/environments/environment_controller_test.go
api/environments/job_handler.go
api/environments/models/job_errors.go

Unit tests for jobs and batches. Does not include tests for legacy jobs.

208004 radix api unit tests

---

api/deployments/models/component_deployment.go
api/environments/environment_controller_test.go
api/environments/job_handler.go
api/pods/pod_handler.go
api/secrets/secret_handler.go
api/utils/sort/pod.go
api/utils/sort/pod_test.go
go.mod
go.sum
radixconfig.yaml

- Add new property FailedCount for job/batch to show number of restarts/retries when backoffLimit is set > 0.
- Show job logs from latest pod

show logs from newest job pod

---

api/deployments/component_controller_test.go
api/deployments/models/component_builder.go
api/deployments/models/component_deployment.go
api/secrets/secret_handler.go
api/secrets/secret_handler_test.go
go.mod
go.sum

* Provide azure key vault names, which uses azure identity
* Extended unit-test
* Corrected ver
* Corrected ver

Fed identity for key vault (#492)

---

CONTRIBUTING.md
README.md
SECURITY.md

* Update readme
* Add security.md
* Add contributing.md

Add repo-info

---

api/applications/applications_controller_test.go
api/applications/applications_handler.go
api/buildstatus/models/buildstatus.go
api/environments/environment_controller_secrets_test.go
api/environments/environment_controller_test.go
api/events/event_handler_test.go
api/jobs/job_controller.go
api/jobs/models/job.go
api/jobs/models/job_summary.go
api/jobs/start_job_handler.go
api/kubequery/deployment.go
api/secrets/models/tls_certificate_test.go
go.mod
go.sum
swaggerui_src/swagger.json

* Added commit ID and tags to promote job and job models

Added commit ID and tags to promote job and job models (#550)

---

.vscode/launch.json
README.md
api/jobs/start_job_handler.go
charts/radix-api-dev/.helmignore
charts/radix-api-dev/Chart.yaml
charts/radix-api-dev/templates/_helpers.tpl
charts/radix-api-dev/templates/deployment.yaml
charts/radix-api-dev/values.yaml
radixconfig.yaml

Revert "Set radix-tekton tag"

---

api/deployments/component_handler.go

* Get HPA by Label selector
* Dont check for possible NotFound error

Release Get HPA by Label selector (#625)

---

api/applications/validate_handler.go
api/deployments/component_controller_test.go
api/deployments/component_handler.go
go.mod
go.sum

Support the Runtime object in RD and RA

Release radix-api

---

api/alerting/handler.go
api/environmentvariables/env_vars_controller_test.go
api/environmentvariables/env_vars_handler_test.go
go.mod
go.sum

replace kube.ApplySecret with UpdateSecret

---

api/applications/applications_handler_factory.go
api/environments/component_handler.go
api/environments/environment_controller_test.go
api/environments/environment_handler.go
api/kubequery/radixapplication.go
api/kubequery/radixapplication_test.go
go.mod
go.sum

* Require Admin to restart Oauth2Proxy

Release Require Admin to restart Oauth2Proxy (#674)

---

api/applications/applications_controller_test.go
api/applications/applications_handler.go
api/applications/models/application_registration.go
api/applications/models/application_registration_builder.go
api/applications/models/application_registration_patch.go
go.mod
go.sum
swaggerui/html/swagger.json

Allow API to manage AD Users and Reader AD Users

---

api/buildstatus/build_status_controller_test.go
api/buildstatus/buildstatus_handler.go
api/buildstatus/models/badges/build-status.svg
api/buildstatus/models/buildstatus.go
api/buildstatus/models/buildstatus_test.go
api/test/mock/buildstatus_mock.go

feat: update style to match github

---

api/defaults/environment_variables.go
api/deployments/models/deployment_builder.go
api/environmentvariables/env_vars_controller_test.go
api/environmentvariables/env_vars_handler.go
api/environmentvariables/env_vars_handler_test.go
go.mod
go.sum

Getting app component's RADIX_ env-vars not from radix-operator logic, but from Kubernetes depployment

fix-public-dns

---

api/applications/applications_controller.go
api/applications/applications_controller_test.go
api/metrics/metrics_handler.go
api/metrics/metrics_handler_test.go
api/metrics/mock/metrics_handler_mock.go
api/metrics/prometheus/prometheus_client.go
api/metrics/prometheus/prometheus_client_test.go

Fixes https://github.com/equinor/radix-web-console/issues/1173

Limit metrics to app and known components

---

api/deployments/models/component_builder.go
api/environments/component_spec.go
api/environments/environment_controller.go
api/environments/environment_controller_secrets_test.go
api/environments/environment_controller_test.go
api/models/auxiliary_resource.go
api/models/secret.go
api/secrets/secret_handler.go
api/secrets/secret_handler_test.go
go.mod
go.sum

Bump radix-operator to v1.75.0
Fix refactored and moved functions in radix-operator

update radix-operator ref and fix errors

---

api/deployments/models/component_builder.go
api/environments/component_spec.go
api/environments/environment_controller.go
api/environments/environment_controller_secrets_test.go
api/environments/environment_controller_test.go
api/models/auxiliary_resource.go
api/models/secret.go
api/secrets/secret_handler.go
api/secrets/secret_handler_test.go
go.mod
go.sum

* update radix-operator ref and fix errors
* bump radix-operator to v1.75.0

update radix-operator ref and fix errors (#745)

---

.vscode/launch.json
api/applications/applications_controller_test.go
api/applications/applications_handler.go
api/applications/start_job_handler.go
api/buildsecrets/buildsecrets_test.go
api/buildstatus/build_status_controller_test.go
api/deployments/deployment_controller_test.go
api/environments/environment_controller_test.go
api/environmentvariables/env_vars_controller_test.go
api/jobs/defaults/defaults.go
api/jobs/internal/pipeline_run_tasks.go
api/jobs/internal/pipeline_runs.go
api/jobs/job_controller.go
api/jobs/job_controller_test.go
api/jobs/job_handler.go
api/jobs/job_handler_test.go
api/jobs/log_handler.go
api/jobs/models/job.go
api/jobs/models/pipeline_run.go
api/jobs/models/pipeline_run_task.go
api/jobs/models/step.go
api/secrets/secret_controller_test.go
api/test/utils.go
go.mod
go.sum
radixconfig.yaml
swaggerui/html/swagger.json

* Removed deprecated fields use
* Removed deprecated fields use
* Added field and logic TriggeredFromWebhook
* Added field and logic TriggeredFromWebhook
* Added field and logic TriggeredFromWebhook
* Fixed sub-pipeline step in the pipeline job summary
* Corrected fake token
* Corrected fake token
* Corrected fake token
* Corrected fake token
* Updated ref
* Step pipeline run replaced with pipeline tasks runs
* Adding subpipeline steps
* Cleanup
* Cleanup
* Cleanup
* Cleanup
* Updated ref

merge-with-radix-tekton (#748)

---

api/models/secret.go

Secrets should have status Pending when data is empty (len==0)

fix: secrets with empty value should have status Pending

---

api/buildsecrets/buildsecrets_handler.go
api/buildsecrets/buildsecrets_test.go

* Update of not existing build secret returns http code 404

750-return-404-on-not-existing-secret (#765)

---

README.md
go.mod
go.sum
internal/config/config.go

* fix: remove unused image tags from config
* fix: update operator and test
* chore: bump dependencies
* deps: update radix-operator

fix: remove unused image tags from config (#763)

---

api/deployments/component_controller_test.go
api/deployments/models/component_deployment.go
api/deployments/models/scheduled_batch.go
api/models/batch.go
go.mod
go.sum
swaggerui/html/swagger.json

Allow env var as job payload https://github.com/equinor/radix/issues/484
Be able to set imageName in addition to imageTagName when starting jobs https://github.com/equinor/radix/issues/485

extend-scheduled-job-description
